### ISSUE TITLE
Wyszukiwanie książki

### ISSUE THREAD

**Issue by janeczkoqba** [Decu98/Learn#1]
https://github.com/Decu98/Learn/blob/273d35595939bc0dfba793e155dc2326841c239f/Biblioteka/library.js#L11-L12

Sprytne rozwiązanie, ale jak ktoś wpisze Autor to każda książka będzie pasować :)
JSON.stringify zamienia obiekt na tekst, który zawiera nazwę oraz wartość zmiennej

`"[{ "Autor": "Adam Mickiewicz" }]"`

**Comment by Decu98** [comment]
Poprawiono, już wyszukiwanie klucza Autor nie jest możliwe :)
