### ISSUE TITLE
Zbędne pobieranie listy z localStorage

### ISSUE THREAD

**Issue by janeczkoqba** [Decu98/Learn#2]
Przy edycji pobierana jest lista z localStorage, a w updateStorage już jest ustawiana lista.

https://github.com/Decu98/Learn/blob/273d35595939bc0dfba793e155dc2326841c239f/Biblioteka/scripts.js#L1-L12

https://github.com/Decu98/Learn/blob/273d35595939bc0dfba793e155dc2326841c239f/Biblioteka/editElement.js#L11

**Comment by Decu98** [comment]
Załatwione, skrócono i usprawniono kod
